"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowLeft, Loader2, Save } from "lucide-react";
import { z } from "zod";
import { toast } from "react-toastify";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useSaveQuestContent } from "@/hooks/use-quests";

const schema = z.object({ source_id: z.string().trim().min(1).max(100), order_number: z.number().int().min(1), name_english: z.string().trim().min(1).max(200), name_indonesia: z.string().trim().min(1).max(200), description_english: z.string().max(5000), description_indonesia: z.string().max(5000), convergence_stage: z.string().max(100), exit_hook_english: z.string().max(5000), exit_hook_indonesia: z.string().max(5000), scope: z.string().max(100), realms_text: z.string().max(200), requirement: z.string().max(100), quest_type: z.string().max(100), objective_english: z.string().max(5000), objective_indonesia: z.string().max(5000), energy_cost: z.number().int().min(0), progress_per_explore: z.number().int().min(0), reward_notes_english: z.string().max(5000), reward_notes_indonesia: z.string().max(5000), boss_english: z.string().max(200), boss_indonesia: z.string().max(200), boss_mechanics_english: z.string().max(5000), boss_mechanics_indonesia: z.string().max(5000), show: z.boolean() });
export type ContentValues = z.infer<typeof schema>;
export const emptyContent: ContentValues = { source_id: "", order_number: 1, name_english: "", name_indonesia: "", description_english: "", description_indonesia: "", convergence_stage: "", exit_hook_english: "", exit_hook_indonesia: "", scope: "REALM_SPECIFIC", realms_text: "solaris", requirement: "REQUIRED", quest_type: "STORY", objective_english: "", objective_indonesia: "", energy_cost: 0, progress_per_explore: 0, reward_notes_english: "", reward_notes_indonesia: "", boss_english: "", boss_indonesia: "", boss_mechanics_english: "", boss_mechanics_indonesia: "", show: true };

export default function ContentForm({ level, mode, endpoint, back, initialValues }: { level: "arc" | "chapter" | "region" | "quest"; mode: "add" | "edit"; endpoint: string; back: string; initialValues: ContentValues }) {
  const router = useRouter();
  const saveContent = useSaveQuestContent();
  const { register, handleSubmit, setError, formState: { errors, isSubmitting } } = useForm<ContentValues>({ resolver: zodResolver(schema), defaultValues: initialValues });
  const submit = handleSubmit(async (values) => { const common = { source_id: values.source_id, order_number: values.order_number, name_english: values.name_english, name_indonesia: values.name_indonesia, description_english: values.description_english, description_indonesia: values.description_indonesia, show: values.show }; const realms = values.realms_text.split(",").map((v) => v.trim().toLowerCase()).filter(Boolean); const payload = level === "arc" ? common : level === "chapter" ? { ...common, convergence_stage: values.convergence_stage, exit_hook_english: values.exit_hook_english, exit_hook_indonesia: values.exit_hook_indonesia } : level === "region" ? { ...common, scope: values.scope, realms, requirement: values.requirement, image: "" } : { source_id: values.source_id, order_number: values.order_number, scope: values.scope, realms, requirement: values.requirement, quest_type: values.quest_type, name_english: values.name_english, name_indonesia: values.name_indonesia, objective_english: values.objective_english, objective_indonesia: values.objective_indonesia, energy_cost: values.energy_cost, progress_per_explore: values.progress_per_explore, reward_notes_english: values.reward_notes_english, reward_notes_indonesia: values.reward_notes_indonesia, boss_english: values.boss_english, boss_indonesia: values.boss_indonesia, boss_mechanics_english: values.boss_mechanics_english, boss_mechanics_indonesia: values.boss_mechanics_indonesia }; try { await saveContent.mutateAsync({ endpoint, method: mode === "add" ? "POST" : "PUT", payload }); toast.success(`${level[0].toUpperCase() + level.slice(1)} ${mode === "add" ? "created" : "updated"} successfully.`); router.push(back); router.refresh(); } catch { const message = `Unable to save ${level}.`; setError("root", { message }); toast.error(message); } }, () => toast.error(`Please correct the highlighted ${level} fields.`));
  const text = (name: keyof ContentValues, label: string) => <div className="grid min-w-0 content-start gap-2"><Label htmlFor={String(name)}>{label}</Label><Input id={String(name)} {...register(name)}/>{errors[name] && <small className="text-sm text-destructive">{String(errors[name]?.message)}</small>}</div>;
  const area = (name: keyof ContentValues, label: string) => <div className="grid min-w-0 content-start gap-2"><Label htmlFor={String(name)}>{label}</Label><Textarea id={String(name)} rows={4} {...register(name)}/></div>;
  return <section className="mx-auto max-w-[960px]"><Button variant="ghost" size="sm" asChild><Link href={back}><ArrowLeft/>Back</Link></Button><div className="my-6 mb-7"><h1>{mode === "add" ? "Add" : "Edit"} {level}</h1></div><form className="mt-6" onSubmit={submit}><Card><CardHeader><CardTitle>{level[0].toUpperCase()+level.slice(1)} details</CardTitle><CardDescription>Content is stored in English and Indonesian.</CardDescription></CardHeader><CardContent><div className="grid grid-cols-2 gap-6 max-[800px]:grid-cols-1">{text("source_id", "Source ID *")}<div className="grid min-w-0 content-start gap-2"><Label htmlFor="order_number">Order number *</Label><Input id="order_number" type="number" min="1" {...register("order_number", { valueAsNumber: true })}/></div>{text("name_english", "Name EN *")}{text("name_indonesia", "Name ID *")}{level !== "quest" && area("description_english", "Description EN")}{level !== "quest" && area("description_indonesia", "Description ID")}{level === "chapter" && <>{text("convergence_stage", "Convergence stage")}{area("exit_hook_english", "Exit hook EN")}{area("exit_hook_indonesia", "Exit hook ID")}</>}{level === "quest" && <>{text("scope", "Scope")}{text("realms_text", "Realms (comma separated)")}{text("requirement", "Required / Optional")}{text("quest_type", "Quest type")}{area("objective_english", "Objective EN")}{area("objective_indonesia", "Objective ID")}<div className="grid min-w-0 content-start gap-2"><Label htmlFor="energy_cost">Energy cost</Label><Input id="energy_cost" type="number" min="0" {...register("energy_cost", { valueAsNumber: true })}/></div><div className="grid min-w-0 content-start gap-2"><Label htmlFor="progress_per_explore">Progress per explore</Label><Input id="progress_per_explore" type="number" min="0" {...register("progress_per_explore", { valueAsNumber: true })}/></div>{area("reward_notes_english", "Reward notes EN")}{area("reward_notes_indonesia", "Reward notes ID")}{text("boss_english", "Boss EN")}{text("boss_indonesia", "Boss ID")}{area("boss_mechanics_english", "Boss mechanics EN")}{area("boss_mechanics_indonesia", "Boss mechanics ID")}</>}</div></CardContent></Card>{errors.root && <p className="text-sm text-destructive">{errors.root.message}</p>}<div className="flex justify-end gap-3 py-6"><Button variant="outline" size="lg" asChild><Link href={back}>Cancel</Link></Button><Button type="submit" size="lg" disabled={isSubmitting}>{isSubmitting ? <Loader2 className="animate-spin"/> : <Save/>}{isSubmitting ? "Saving…" : `Save ${level}`}</Button></div></form></section>;
}
