"use client";

import { Input } from "@/components/ui/input";

import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";

import Link from "next/link";
import { useParams, useSearchParams } from "next/navigation";
import { ArrowLeft, ArrowRight, Pencil, Plus, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useQuestArc, useQuestArcs, useQuestChapter, useQuestChapters, useQuestItems, useQuestRegion, useQuestRegions } from "@/hooks/use-quests";
import { EmptyState, PageError, PageLoading } from "@/components/admin/page-state";

export function QuestArcsBrowser() {
  const query = useQuestArcs();
  if (query.isPending) return <PageLoading label="Loading quest arcs…"/>;
  if (query.isError || !query.data) return <PageError message="Unable to load quest arcs." />;
  return <section><div className="flex w-full items-center justify-between gap-6 max-[600px]:flex-col max-[600px]:items-start"><div><p className="text-xs font-semibold text-muted-foreground">World</p><h1>Quest arcs</h1><p className="text-muted-foreground">Campaign hierarchy: Arc → Chapter → Region → Quest.</p></div><Button asChild><Link href="/admin/quests/new"><Plus/>Add arc</Link></Button></div>{query.data.data.length ? <div className="mt-7 grid grid-cols-[repeat(auto-fit,minmax(300px,1fr))] gap-[18px]">{query.data.data.map((arc) => <Card className="min-h-[260px] p-6" key={arc._id}><div className="w-max rounded-full bg-[var(--primary-soft)] px-2.5 py-1 text-xs font-bold text-primary">Arc {arc.order_number}</div><small>{arc.source_id}</small><h2>{arc.name_english}</h2><p className="text-muted-foreground">{arc.name_indonesia}</p><p>{arc.description_english}</p><footer><span>{arc.chapter_count} chapters</span><div className="flex gap-2 whitespace-nowrap"><Button size="sm" variant="outline" asChild><Link href={`/admin/quests/${arc._id}/edit`}><Pencil/>Edit</Link></Button><Button size="sm" asChild><Link href={`/admin/quests/${arc._id}`}>Open arc <ArrowRight/></Link></Button></div></footer></Card>)}</div> : <div className="mt-10"><EmptyState title="No quest arcs yet" description="Use Add arc to begin the campaign hierarchy."/></div>}</section>;
}

export function ChaptersBrowser() {
  const { arcId = "" } = useParams<{ arcId: string }>(); const arc = useQuestArc(arcId); const chapters = useQuestChapters(arcId);
  if (arc.isPending || chapters.isPending) return <PageLoading label="Loading chapters…"/>;
  if (arc.isError || chapters.isError || !arc.data || !chapters.data) return <PageError message="Unable to load chapters." />;
  return <section><Button variant="ghost" size="sm" asChild><Link href="/admin/quests"><ArrowLeft/>Back to arcs</Link></Button><div className="flex w-full items-center justify-between gap-6 max-[600px]:flex-col max-[600px]:items-start my-7"><div><p className="text-xs font-semibold text-muted-foreground">{arc.data.source_id}</p><h1>{arc.data.name_english}</h1><p className="text-muted-foreground">{arc.data.name_indonesia} · {chapters.data.total} chapters</p></div><Button asChild><Link href={`/admin/quests/${arcId}/chapters/new`}><Plus/>Add chapter</Link></Button></div><Table><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Chapter</TableHead><TableHead>Stage</TableHead><TableHead>Regions</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{chapters.data.data.length ? chapters.data.data.map((chapter) => <TableRow key={chapter._id}><TableCell>{chapter.order_number}</TableCell><TableCell className="min-w-[230px]"><small>{chapter.source_id}</small><strong>{chapter.name_english}</strong><small>{chapter.name_indonesia}</small><small>{chapter.description_english}</small></TableCell><TableCell><span className="inline-flex rounded-full bg-[var(--primary-soft)] px-2 py-1 text-[11px] font-semibold lowercase text-primary">{chapter.convergence_stage}</span></TableCell><TableCell>{chapter.region_count}</TableCell><TableCell><div className="flex gap-2 whitespace-nowrap"><Button size="sm" variant="outline" asChild><Link href={`/admin/quests/${arcId}/${chapter._id}/edit`}><Pencil/>Edit</Link></Button><Button size="sm" asChild><Link href={`/admin/quests/${arcId}/${chapter._id}`}>Open chapter <ArrowRight/></Link></Button></div></TableCell></TableRow>) : <TableRow><TableCell colSpan={5} className="p-8 text-center text-muted-foreground">No chapters yet. Use Add chapter to continue this arc.</TableCell></TableRow>}</TableBody></Table></section>;
}

export function RegionsBrowser() {
  const { arcId = "", chapterId = "" } = useParams<{ arcId: string; chapterId: string }>(); const chapter = useQuestChapter(chapterId); const regions = useQuestRegions(chapterId);
  if (chapter.isPending || regions.isPending) return <PageLoading label="Loading regions…"/>;
  if (chapter.isError || regions.isError || !chapter.data || !regions.data) return <PageError message="Unable to load regions." />;
  return <section><Button variant="ghost" size="sm" asChild><Link href={`/admin/quests/${arcId}`}><ArrowLeft/>Back to chapters</Link></Button><div className="flex w-full items-center justify-between gap-6 max-[600px]:flex-col max-[600px]:items-start my-7"><div><p className="text-xs font-semibold text-muted-foreground">{chapter.data.source_id}</p><h1>{chapter.data.name_english}</h1><p className="text-muted-foreground">{chapter.data.name_indonesia} · {regions.data.total} regions</p></div><Button asChild><Link href={`/admin/quests/${arcId}/${chapterId}/regions/new`}><Plus/>Add region</Link></Button></div><Table><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Region</TableHead><TableHead>Realm access</TableHead><TableHead>Scope</TableHead><TableHead>Type</TableHead><TableHead>Quests</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{regions.data.data.length ? regions.data.data.map((region) => <TableRow key={region._id}><TableCell>{region.order_number}</TableCell><TableCell className="min-w-[230px]"><small>{region.source_id}</small><strong>{region.name_english}</strong><small>{region.name_indonesia}</small><small>{region.description_english}</small></TableCell><TableCell>{region.realms.join(", ")}</TableCell><TableCell><span className="inline-flex rounded-full bg-[var(--primary-soft)] px-2 py-1 text-[11px] font-semibold lowercase text-primary">{region.scope}</span></TableCell><TableCell>{region.requirement}</TableCell><TableCell>{region.quest_count}</TableCell><TableCell><div className="flex gap-2 whitespace-nowrap"><Button size="sm" variant="outline" asChild><Link href={`/admin/quests/${arcId}/${chapterId}/${region._id}/edit`}><Pencil/>Edit</Link></Button><Button size="sm" asChild><Link href={`/admin/quests/${arcId}/${chapterId}/${region._id}`}>Quests <ArrowRight/></Link></Button></div></TableCell></TableRow>) : <TableRow><TableCell colSpan={7} className="p-8 text-center text-muted-foreground">No regions yet. Use Add region to continue this chapter.</TableCell></TableRow>}</TableBody></Table></section>;
}

export function QuestsBrowser() {
  const { arcId = "", chapterId = "", regionId = "" } = useParams<{ arcId: string; chapterId: string; regionId: string }>(); const params = useSearchParams(); const search = (params.get("search") || "").slice(0, 100); const queryString = new URLSearchParams({ limit: "100", ...(search ? { search } : {}) }).toString(); const region = useQuestRegion(regionId); const quests = useQuestItems(regionId, queryString); const path = `/admin/quests/${arcId}/${chapterId}/${regionId}`;
  if (region.isPending || quests.isPending) return <PageLoading label="Loading quests…"/>;
  if (region.isError || quests.isError || !region.data || !quests.data) return <PageError message="Unable to load quests." />;
  return <section><Button variant="ghost" size="sm" asChild><Link href={`/admin/quests/${arcId}/${chapterId}`}><ArrowLeft/>Back to regions</Link></Button><div className="flex w-full items-center justify-between gap-6 max-[600px]:flex-col max-[600px]:items-start my-7"><div><p className="text-xs font-semibold text-muted-foreground">{region.data.source_id}</p><h1>{region.data.name_english}</h1><p className="text-muted-foreground">{region.data.name_indonesia} · {region.data.realms.join(", ")} · {quests.data.total} quests</p></div><Button asChild><Link href={`${path}/quests/new`}><Plus/>Add quest</Link></Button></div><form className="my-6 flex flex-wrap items-center gap-3"><Input name="search" placeholder="Search quest…" defaultValue={search}/><Button type="submit" variant="outline"><Search/>Search</Button></form><Table><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Quest</TableHead><TableHead>Type</TableHead><TableHead>Energy</TableHead><TableHead>Progress</TableHead><TableHead>Requirement</TableHead><TableHead>Details</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{quests.data.data.length ? quests.data.data.map((quest) => <TableRow key={quest._id}><TableCell>{quest.order_number}</TableCell><TableCell className="min-w-[230px]"><small>{quest.source_id}</small><strong>{quest.name_english}</strong><small>{quest.name_indonesia}</small><small>{quest.objective_english}</small></TableCell><TableCell><span className="inline-flex rounded-full bg-[var(--primary-soft)] px-2 py-1 text-[11px] font-semibold lowercase text-primary">{quest.quest_type}</span></TableCell><TableCell>{quest.energy_cost}</TableCell><TableCell>{quest.progress_per_explore}</TableCell><TableCell>{quest.requirement}</TableCell><TableCell><details><summary>View</summary><dl><dt>Rewards</dt><dd>{quest.reward_notes_english}</dd><dt>Boss</dt><dd>{quest.boss_english}</dd><dt>Prerequisites</dt><dd>{JSON.stringify(quest.prerequisites)}</dd><dt>Dialogues</dt><dd>{quest.dialogues.length}</dd></dl></details></TableCell><TableCell><Button size="sm" variant="outline" asChild><Link href={`${path}/${quest._id}/edit`}><Pencil/>Edit</Link></Button></TableCell></TableRow>) : <TableRow><TableCell colSpan={8} className="p-8 text-center text-muted-foreground">{search ? "No quests match this search. Clear the search to view all quests." : "No quests yet. Use Add quest to populate this region."}</TableCell></TableRow>}</TableBody></Table></section>;
}
